theme: jekyll-theme-minimal
title: 5th Times the Charm - Team Website
description: A team website for the 5th Senior Project of Beyond RGB.
markdown: GFM
# Add collections for submissions
collections:
  submissions:
    output: true
    permalink: /submissions/:name/
